time = input("please enter a time ")
items = input("please enter items ")
name = input("please enter a name ")
scream = input("please enter a scream ")
action = input("please enter an action ")

print ("It was " + str(time) + " o'clock when I heard a knock at the door.")
print ("I opened the door and there was a box full of " + items + " with a note saying From Mr " + name.title())
print ("Just as I closed the door I heard a scream " + scream.upper())
print ("I froze in place and all I could do was " + action)